name: apphud_plus
description: A package for listening to Apphud notifications and purchasing products.
version: 0.0.7
homepage: https://github.com/glebosotov/flutter_apphud_plus

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      # android:
      #   package: com.example.apphud_plus
      #   pluginClass: ApphudPlusPlugin
      ios:
        pluginClass: ApphudPlusPlugin
      # linux:
      #   pluginClass: ApphudPlusPlugin
      # macos:
      #   pluginClass: ApphudPlusPlugin
      # windows:
      #   pluginClass: ApphudPlusPluginCApi

